<?php

/**
 * @file
 * Contains Layout Paragraphs Restrictions module.
 */

use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_preprocess_layout_paragraphs_builder().
 */
function mercury_editor_restrictions_preprocess_layout_paragraphs_builder(&$variables) {
  $restrictions = \Drupal::configFactory()->get('mercury_editor_restrictions.settings')->get('restrictions');
  $layout = $variables['layout_paragraphs_layout'];
  $variables['#attached']['drupalSettings']['lpBuilder']['restrictions'][$layout->id()] = array_values($restrictions);
  $variables['#attached']['library'][] = 'mercury_editor_restrictions/restrictions';
}

/**
 * Implements hook_preprocess_paragraph().
 */
function mercury_editor_restrictions_preprocess_paragraph(&$variables) {
  if (!empty($variables['paragraph']->_layoutParagraphsBuilder)) {
    /** @var Paragraph $paragraph */
    $paragraph = $variables['paragraph'];
    $variables['attributes']['data-me-component-type'] = $paragraph->bundle();
    $behaviorSettings = $paragraph->getAllBehaviorSettings();
    foreach ($behaviorSettings['style_options'] ?? [] as $style_option) {
      if (!empty($style_option['component_variation'])) {
        $variables['attributes']['data-me-component-type'] .= '__' . $style_option['component_variation'];
      }
    }
  }
}
